apiVersion: apps/v1
kind: Deployment
metadata:
  name: mendix-deployment
spec:
  selector:
    matchLabels:
      name: mendix-pod
  template:
    metadata:
      labels:
        name: mendix-pod
    spec:
      containers:
      - name: mendix-container
        image: marceloweb/demo-app-mendix:v3.4.1
        ports:
          - containerPort: 8080
          - containerPort: 6831
            protocol: UDP
        args: ["--collector.host-port=jaeger-collector:14267"]
        env:
         - name: MXRUNTIME_DatabaseType
           value: ${MXRUNTIME_DatabaseType}
         - name: MXRUNTIME_DatabaseUserName
           value: ${MXRUNTIME_DatabaseUserName}
         - name: MXRUNTIME_DatabasePassword
           value: ${MXRUNTIME_DatabasePassword}
         - name: MXRUNTIME_DatabaseHost
           value: ${MXRUNTIME_DatabaseHost}
         - name: MXRUNTIME_DatabaseName
           value: ${MXRUNTIME_DatabaseName}
         - name: ADMIN_PASSWORD
           value: ${ADMIN_PASSWORD}